### ISSUE TITLE
PRのCIで public/mockServiceWorker.js が最新になるようにしたい

### ISSUE THREAD

**Issue by reiroop** [traPtitech/Jomon-UI#344]
npm run gen-api で public/mockServiceWorker.js に変更が入るようなPRに気付けるようにしたい

以下のようにCIでgen-apiしてgit diffを見ると良さそう
```
jobs:
  genApi:
    name: Generate APIs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: npm run gen-api
      - name: Check for differences in generated APIs
        run: |
          git diff --exit-code ./src/lib/apis/generated || {
            echo "Generated APIs are outdated or modified. Please run 'npm run gen-api' and commit the changes."
            exit 1
          }
```
